# Prototype ESB in Openshift with Fuse Integration Services 2.0

This repository holds the prototype for the master thesis __Implementation of an Enterprise Service Bus with OpenShift__
which is public available on link:++https://github.com/cchet-thesis-msc/thesis++[Github]. The prototype uses the RedHat tooling __Fuse Integration Services 2.0__ which consists of
a Maven Plugin (Fabric8) and Openshift Builder-Images, which allow to manage a integration service
via a Maven Build. This readme provides introductions to setup and run the prototype on a
Windows 10 Host. +

## Windows 10 Setup
This section will describe the setup of the Windows 10 environment. The following applications and features need
to be enabled, installed and configured. +

. Follow the instructions available link:++https://docs.microsoft.com/en-us/windows/wsl/install-win10++[here] to
  install and enable WSL. During the development, the Ubuntu Linux-Image has been used. +
. Follow the instruction available link:++https://docs.docker.com/docker-for-windows/install/#install-docker-for-windows-desktop-app++[here] to
  install and configure __Docker For Windows__. The installer will ask you to enable **HyperV** Windows-Feature, which will
  prevent VMWare or VirtualBox from working.
. Download link:++https://www.python.org/downloads/windows/++[Python 3.x] for Windows and install it.
.. If not already added during installation process, add Python binaries to Windows $PATH.
.. Install the following Python packages of link:++https://github.com/getwarped/powershift++[Powershift],
   which are used to manage the local Openshift Cluster. Install these packages via ``pip install <PACKAGE_NAME>``.
... __powershift__, is the base package.
... __powershift-cli__, is the base CLI implementation.
... __powershift-cluster__, provides CLI for managing __oc cluster__ created clusters.
... __powershift-image__, provides CLI for managing S2I Images and Builds.

## Docker For Windows Setup
This section will describe the setup of Docker for Windows.

. Go to __General__ and enable **Expose daemon via tcp://...**, so that WSL can access the Docker Daemon.
. Go to __Advanced__ and setup the available CPU and Memory. **(CPU: 7, RAM 7GB, DISK 112GB)**
. Go to __Daemon__ enable **Advanced Features** and replace the Json Data with the following
[source,json]
{
  "registry-mirrors": [],
  "insecure-registries": [
    "172.30.0.0/16"
  ],
  "debug": false,
  "experimental": false,
  "selinux-enabled": false
}

The Docker Daemon can now be accessed via the exposed URL, which will be done via the WSL. The private registry
is used by Openshift for storing Docker Images and selinux is disabled, because there is no way to get into the backing VM of Docker For Windows.

## WSL setup
This section will describe the setup of the WSL environment.

. Execute ``sudo apt install docker.io`` to install Docker on Ubunto 18.04 WSL-Image.
. Open a Powershell, execute ``bash`` and setup the Linux user
. Add ``export DOCKER_HOST=tcp://127.0.0.1:2375`` to ``~/.bashrc`` of your Linux user to point to Windows Docker-Daemon. Don't use **localhost**
  because this points to WSL localhost.

Docker commands executed in the WSL, will actual be executed on the Windows Docker-Host, which is
located in a HyperV VM.


## Setup local Openshift Cluster
This section describes how to setup a local Openshift Cluster with **powershift** on a Windows 10 Host.

Open a Powershell Window and execute ``powershift cluster up <PROFILE_NAME>`` to start local Openshift Cluster.
This command will start a busybox container before starting the Openshift Cluster,
whereby busybox will provide the filesystem, where the configurations of the profile are stored. +

The following shows the output of  ``powershift cluster up prototype``, when the profile doesn't exist yet.
[source,bash]
----
C:\>powershift cluster up prototype
    Creating
    Unable to find image 'busybox:latest' locally
    latest: Pulling from library/busybox
    75a0e65efd51: Pull complete
    Digest: sha256:d21b79794850b4b15d8d332b451d95351d14c951542942a816eea69c9e04b240
    Status: Downloaded newer image for busybox:latest
    error: server took too long to respond with version information.
    oc cluster up
      --host-data-dir "/var/lib/powershift/profiles/prototype/data"
      --host-config-dir "/var/lib/powershift/profiles/prototype/config"
      --host-pv-dir "/var/lib/powershift/profiles/prototype/volumes"
      --use-existing-config
      --forward-ports=false
    Pulling image openshift/origin:v3.9.0
    Pulled 1/4 layers, 50% complete
    Pulled 4/4 layers, 100% complete
    Extracting
    Image pull complete
    Using Docker shared volumes for OpenShift volumes
    Using 10.0.75.2 as the server IP
    Starting OpenShift using openshift/origin:v3.9.0 ...
    OpenShift server started.

    The server is accessible via web console at:
        https://10.0.75.2:8443

    You are logged in as:
        User:     developer
        Password: <any value>

    To login as administrator:
        oc login -u system:admin

    cluster role "sudoer" added: "system:authenticated"
    Restarting
    Stopping
    Starting
    oc cluster up
      --host-data-dir "/var/lib/powershift/profiles/prototype/data"
      --host-config-dir "/var/lib/powershift/profiles/prototype/config"
      --host-pv-dir "/var/lib/powershift/profiles/prototype/volumes"
      --use-existing-config
      --forward-ports=false
    Using Docker shared volumes for OpenShift volumes
    Using 10.0.75.2 as the server IP
    Starting OpenShift using openshift/origin:v3.9.0 ...
    OpenShift server started.

    The server is accessible via web console at:
        https://10.0.75.2:8443

    Cluster "powershift-prototype" set.
    User "developer@powershift-prototype" set.
    Context "powershift-prototype" modified.
    Switched to context "powershift-prototype".
    Started
----

## Repository Structure
This section describes the structure of the prototype repository, which holds all needed resources. +

* **.idea** is the IntelliJ directory holding IntelliJ Run-Configurations.
* **/docker** is the directory which holds all Docker relevant resources.
* **/docker/<SERVICE_NAME>** is the directory holding all service relevant Openshift related resources.
* **/openshift** is the directory which contains all Openshift relevant resource, which are managed outside of
  the integration service code bases.
* **/openshift/<SERVICE_NAME>** is the directory holding all service relevant Openshift related resources.
* **/openshift/<SERVICE_NAME>/config/** is the directory holding all service relevant configurations over all stages.
* **/openshift/<SERVICE_NAME>/config/<STAGE>** is the directory holding all service relevant configuration for a specific stage.
* **/services** is the directory holding the service code bases
* **/services/<SERVICE_NAME>** is the directory holding the service related code base.

The service code bases are completely separated from each other and would normally reside in their own repositories, but
for demonstration purpose all resources where kept in one repository. See the following links for the documentation
of the different parts of the prototype. +

## Run prototype
This section describes how to run the prototype on a running Openshift Cluster. +

* Open a Powershell and execute ``bash`` to get to the WSL
* Login to the Openshift Cluster via ``oc login``
* Switch to the project, the prototype should be deployed on
* Execute ``STAGE=local openshift/esb-infra.sh createAll`` to create all infrastructure services such as Graylog
* Wait until all infrastructure services are up
* Execute ``STAGE=local openshift/esb.sh createAll`` to create all integration services
* Wait until all integration services are up

See link:services/README.adoc[here] for documentation how to prepare and access the deployed integration services. +
See link:openshift/README.adoc[here] for documentation how to prepare the deployed infrastructure services. +

## Further documentation

* link:services/README.adoc[services/README.adoc] holds the documentation of the implemented integration services.
* link:openshift/README.adoc[openshift/README.adoc] holds the documentation of the implemented resources, which manage
  a Openshift Project.
* link:https://maven.fabric8.io/[fabric8-maven-plugin] holds the documentation of the fabric8 maven plugin
* link:http://wildfly-swarm.io/[Thorntail.io] is the home page of Thorntail  __(formerly known as Wildfly-Swarm)__
* link:https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html/fuse_integration_services_2.0_for_openshift/index[Fuse Integration Services 2.0] is the Red Hat guide for
  Fuse Integration Services 2.0
