kind: "Template"
apiVersion: "v1"
metadata:
  name: "ESB-secrets"

parameters:
  - name: "APP_NAME"
    displayName: "App name"
    description: "The name of the related app"
    required: true

  - name: "SSH_SECRET_NAME"
    displayName: "SSH secret name"
    description: "The name of the ssh secret"
    required: true

  - name: "DHCP_SECRET_NAME"
    displayName: "DHCP secret name"
    description: "The name of the dhcp secret"
    required: true

  - name: "ACS_SECRET_NAME"
    displayName: "ACS secret name"
    description: "The name of the acs secret"
    required: true

  - name: "IMPL_SECRET_NAME"
    displayName: "Incognito IMPL secret name"
    description: "The name of the incognito impl secret"
    required: true

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${SSH_SECRET_NAME}"
      labels:
        app: "${APP_NAME}"
    stringData:
      incognito.sshproxy.ophost: "localhost"
      incognito.sshproxy.exthost: "localhost"
      incognito.sshproxy.host: "localhost"
      incognito.sshproxy.user: "jenkins"
      incognito.sshproxy.pwd: "jenkins"
      incognito.sshproxy.script: "/scripts/"

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${ACS_SECRET_NAME}"
      labels:
        app: "${APP_NAME}"
    stringData:
      acs.remote.host: "localhost"
      acs.remote.user: "service_esb"
      acs.remote.pwd: "service_esb"
      acs.remote.token: "IncognitoUms auth"

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${DHCP_SECRET_NAME}"
      labels:
        app: "${APP_NAME}"
    stringData:
        dhcp.remote.user: "service_esb"
        dhcp.remote.password: "service_esb"

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${IMPL_SECRET_NAME}"
      labels:
        app: "${APP_NAME}"
    stringData:
      rest.client.base.ssh: http://liwestfsw-incognito-ssh:8080/rest-api
      rest.client.base.dhcp: http://liwestfsw-incognito-dhcp:8080/rest-api
      rest.client.base.dsl: http://liwestfsw-incognito-dsl:8080/rest-api
      rest.client.base.snmp: http://liwestfsw-incognito-snmp:8080/rest-api
      rest.client.base.mps: http://liwestfsw-incognito-mps:8080/rest-api
      rest.client.base.db: http://liwestfsw-incognito-db:8080/rest-api
      rest.client.base.acs: http://liwestfsw-incognito-acs:8080/rest-api
