spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 5
      intervalSeconds: 5
      timeoutSeconds: 120
  replicas: 1
  template:
    spec:
      volumes:
        - name: app-config
          secret:
            secretName: ${oc.secret-service-app}
        - name: keycloak-config
          secret:
            secretName: ${oc.secret-service-app-keycloak}
      containers:
        - name: ${project.artifactId}
          resources:
            requests:
              cpu: "0.2"
              memory: 128Mi
            limits:
              cpu: "2.0"
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            successThreshold: 2
            failureThreshold: 20
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9990
              protocol: TCP
          volumeMounts:
            - name: app-config
              mountPath: ${oc.secret-service-app.dir}
            - name: keycloak-config
              mountPath: ${oc.secret-service-app-keycloak.dir}
          env:
              # Necessary, otherwise java console won't work in Openshift
            - name: "AB_JOLOKIA_HTTPS"
              value: "true"
            - name: "AB_JOLOKIA_OFF"
              value: "false"
            - name: "AB_PROMETHEUS_OFF"
              value: "false"
            - name: "JAVA_MAX_MEM_RATIO"
              value: "100"
            - name: "JAVA_OPTIONS"
              value: "-Djava.net.preferIPv4Stack=true \
                      -Dswarm.project.stage=openshift"
            - name: "JAEGER_HOST"
              valueFrom:
                secretKeyRef:
                  name: ${oc.secret-service-app}
                  key: jaeger.host
            - name: "JAEGER_PORT"
              valueFrom:
                secretKeyRef:
                  name: ${oc.secret-service-app}
                  key: jaeger.port
